### ISSUE TITLE
Should we use a CDN?

### ISSUE THREAD

**Issue by jackdalton** [sasha240100/WhitestormJS#11]
Should we use a CDN such as [jsDelivr](http://www.jsdelivr.com/) for hosting WhitestormJS?

I've dealt with jsDelivr before, and can easily add WhitestormJS to their services.

**Comment by jackdalton** [comment]
If so, [I've got the PR ready](https://github.com/jackdalton/jsdelivr/tree/master/files/whitestormjs).

**Comment by sasha240100** [comment]
@jackdalton Good idea! Let's add.

**Comment by jackdalton** [comment]
[Pulled](https://github.com/jsdelivr/jsdelivr/pull/8149).

**Comment by jackdalton** [comment]
[Project added](http://www.jsdelivr.com/projects/whitestormjs).
