### ISSUE TITLE
Everything breaks in < Chrome 45 due to use of Object.assign

### ISSUE THREAD

**Issue by jackdalton** [sasha240100/WhitestormJS#16]
As the title states, due to the use of ES6 feature [`Object.assign`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) [here](https://github.com/sasha240100/WhitestormJS/blob/master/src/API/Construct.js#L79) and [here](https://github.com/sasha240100/WhitestormJS/blob/master/src/Ground/addGround.js#L159) it becomes impossible to use WhitestormJS in any version of Chrome under 45.

[Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility).

We can fix this by including [this polyfill](https://gist.github.com/jackdalton/e14829e2316e7ee33f51).

**Comment by sasha240100** [comment]
I will add [this](https://github.com/ljharb/object.assign/blob/master/implementation.js) later.
